steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-sms:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-sms:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-sms'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-sms:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY},TWILIO_ACCOUNT_SID=${_TWILIO_ACCOUNT_SID},TWILIO_AUTH_TOKEN=${_TWILIO_AUTH_TOKEN},TWILIO_PHONE_NUMBER=${_TWILIO_PHONE_NUMBER},OPENAI_ASSISTANT_ID=${_OPENAI_ASSISTANT_ID},WEBHOOK_URL=${_WEBHOOK_URL},USE_MAKE_WEBHOOK=${_USE_MAKE_WEBHOOK}'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ai-sms:$COMMIT_SHA'

# Set logging option to address service account error
options:
  logging: CLOUD_LOGGING_ONLY
